# default parameters for lane_filter/lane_filter_node

#propagation
predict_frequency: 10.0 # in Hz
debug : True
lane_filter_histogram_configuration:
  mean_d_0: 0.0
  mean_phi_0: 0.0
  sigma_d_0: 0.0001
  sigma_phi_0: 0.00002
  delta_d: 0.02 #0.01 #0.02
  delta_phi: 0.05
  d_max: 0.3
  d_min: -0.3 #-1.5
  phi_min: -1.5 #-1.5
  phi_max: 1.5 #1.5
  cov_v: 0.5
  linewidth_white: 0.05
  linewidth_yellow: 0.025
  lanewidth: 0.23
  min_max: 0.1
  sigma_d_mask: 0.1
  sigma_phi_mask: 0.2
  range_min: 0.2
  range_est: 0.45 #0.33
  range_max: 0.6
  weight_yellow: 1.0
  weight_white: 1.0